baseURL: /
languageCode: en-us
title: "On-the-Fly Syntax Highlighting Using Neural Networks: Replication Package"
theme: book

disableKinds:
  - taxonomy
  - taxonomyTerm

menu:
  after:
    - name: "‚¨áÔ∏è Source Code"
      url: "https://github.com/MEPalma/HLNN-ReplicationPackage"
      weight: 1
    - name: "üíΩ Data"
      url: "https://zenodo.org/record/zenodo.6949491"
      weight: 2

params:
  BookLogo: logo.png
